language: go

sudo: false

go:
  - "1.10.x"

sudo: required

services:
  - docker

install:
  - docker build -f docker/prod.Dockerfile -t ethereum/sharding-p2p:latest .
  - docker run -d --name p2p ethereum/sharding-p2p:latest
  - make deps

before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python3.6
  - go get ./...

script:
  - go test -v ./...
  - ./cli-example/iterate_all_rpc_call.sh
  - docker ps | grep -q p2p
